# Generated by Django 6.0.4 on 2026-04-28 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
